### ISSUE TITLE
ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#1018]
Hola! estoy desarrollando un proyecto en donde uso sockets, threading y matplotlib. Basicamente se envían datos de un computador a otro por medio de la red local y el cliente plotea estos datos en tiempo real. El servidor obtiene estos datos por medio de un thread y los envía por medio de otro thread. El cliente, ocupa un thread para recibir los datos y grabarlos en un csv, y ocupa otro thread para ir graficando los datos guardados. El tema es que cuando probé ambos códigos en el mismo computador (con socket.gethostname()) con 2 consolas separadas funcionó bien. Sin embargo, al momento de probarlo entre mi computador y una Raspberry Pi, me tira error. Luego de leer el error, lo único que se me puede ocurrir es que haya una incompatibilidad entre los módulos que ocupo en mi computador a los de la Raspberri, pero no sé. Adjunto el error a continuación:

```
WARNING: QApplication was not created in the main() thread.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/cris/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/cris/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "client_side.py", line 14, in plot_data
    plt.show()
  File "/home/cris/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 263, in show
    return _show(*args, **kw)
  File "/home/cris/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 413, in wrapper
    return func(*args, **kwargs)
  File "/home/cris/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3302, in show
    cls.mainloop()
  File "/home/cris/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 1088, in mainloop
    signal.signal(signal.SIGINT, signal.SIG_DFL)
  File "/home/cris/anaconda3/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

^CException ignored in: <module 'threading' from '/home/cris/anaconda3/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/home/cris/anaconda3/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/home/cris/anaconda3/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/home/cris/anaconda3/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by dlmed** [comment]
solucionado!

**Comment by jtmeyer98** [comment]
Como lo solucionaste?? Tengo el mismo error

**Comment by dlmed** [comment]
Hola, en este caso estaba haciendo un programa nada que ver con el curso, pero de todas formas: se arregló al implementar la función que me estaba dando problemas en el main thread y no en un thread aparte.
