### ISSUE TITLE
Duda con hasheables

### ISSUE THREAD

**Issue by crow-rojas** [IIC2233/syllabus#113]
¡Hola! Estaba haciendo la actividad del semestre pasado para preparar la actividad de mañana y se me generó una duda respecto a los defaultdic y elementos hasheables.

Para ahorrar tiempo y no escribir tanto código, voy a generalizar mi problema: Tengo un diccionario  el cual cada llave es un 'str' y cada valor es una 'namedtuple', la cual tiene 4 "atributos" (str, int, set, set). Un ejemplo de un print:

`
35: NamedTupleExample(string='IIC2233', entero=3, set1={'h', 'o'}, set2={'l', 'a'})
`

Ahora, luego de tener este diccionario, quiero otro en el que tenga nuevamente 'str' como llaves y en los valores cada uno sea un 'set' que contenga varias de las 'namedtuple' mencionadas antes, agregándolas según el identificador del primer diccionario. Que pasa, que en mi código creo un defaultdic con set (`defaultdic(set)`), pero al ir viendo en mi primer diccionario las llaves que me interesan y hacer un `diccionario_2[id_2].add[diccionario_1[id_1]` tengo el siguiente error:

`
Traceback (most recent call last):
  File "d:/Git Repositories/syllabus-2019-1/Actividades/AC01/test.py", line 46, in <module>
    fam = funcion_1('texto2.txt', diccionario_1)
  File "d:/Git Repositories/syllabus-2019-1/Actividades/AC01/test.py", line 41, in funcion_1
    diccionario_2[id_2].add(diccionario_1[id_1])
TypeError: unhashable type: 'set'
`

En resumen quiero agregar al valor de mi segundo diccionario (que por default es un set), una 'namedtuple' descrita como antes que pertenece al primer diccionario, pero no puedo. Cabe decir que si en vez de poner `defaultdic(set)` uso `defaultdic(list` y hago append, en vez de add, el programa funciona correctamente, pero me gustaría tener un set de las namedtuples en vez de una lista de éstos (si es posible).

Espero haberme explicado bien y que se entienda. ¡Si alguien me explica porque sucede esto muchas gracias!

**Comment by crow-rojas** [comment]
¡Gracias @javieraochoa!
