### ISSUE TITLE
retornar y usar los valores de las super clases en multiherencia?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#124]
Como se podria hacer que una clase `C` herede la clase `A` y `B` donde las tres tienen el metodo `metodo`, pero que la tercera use el valor de las otras dos super clases? Ejemplo

`metodo` de clase `A` retorna 1
`metodo` de clase `B` retorna 2
_Necesito_ que clases `C` retorne 1 + 2 = 3

Lo que he intente fue lo siguiente

```python
from abc import ABCMeta


class Base(metaclass=ABCMeta):
    def metodo(self):
        pass

class A(Base):
    def metodo(self):
        return 1
class B(Base):
    def metodo(self):
        return 2

class C(A, B):
    def metodo(self):
        a,b = super().metodo()
        return a + b

c = C()
print(c.metodo())       
```
Sin embargo, me aparece el siguiente error.

```
"C:\Program Files\Python36\python.exe" C:/Users/nicol/.PyCharm2018.1/config/scratches/scratch_1.py
Traceback (most recent call last):
  File "C:/Users/nicol/.PyCharm2018.1/config/scratches/scratch_1.py", line 21, in <module>
    print(c.metodo())
  File "C:/Users/nicol/.PyCharm2018.1/config/scratches/scratch_1.py", line 17, in metodo
    a,b = super().metodo()
TypeError: 'int' object is not iterable

Process finished with exit code 1
```
Hay alguna forma de lograr lo anterior?

**Comment by nmaturana97** [comment]
Podrias hacerlo de esta forma:
```
from abc import ABCMeta


class Base(metaclass=ABCMeta):
    def metodo(self):
        pass

class A(Base):
    def metodo(self):
        return 1
class B(Base):
    def metodo(self):
        return 2

class C(A, B):
    def metodo(self):
        a = A().metodo() + B().metodo()
        return a

c = C()
print(c.metodo())

```

**Comment by fgbruna** [comment]
Basta con que llames a cada metodo directamente:
```python
def metodo(self):
       return A.metodo(self) + B.metodo(self)
```

**Comment by naquiroz** [comment]
@nmaturana97 el problema de eso es que se instancia dos veces Base o no? No hay forma de usar la misma instancias? Pongo un ejemplo mas complejo

```python
from abc import ABCMeta


class Base(metaclass=ABCMeta):
    def __init__(self):
        self.a = 1
    def metodo(self):
        pass

class A(Base):
    def __init__(self):
        super().__init__()
        self.a = 2
        
    def metodo(self):
        self.a += 1
        return  self.a
class B(Base):
    def __init__(self):
        super().__init__()
        self.a = 2
        
    def metodo(self):
        self.a += 1
        return self.a

class C(A, B):
    def metodo(self):
        a,b = super().metodo()
        return a + b

c = C()
print(c.metodo())
```
Aqui yo quiero que el resultado sea que `metodo` de A retorne 3, pero como ahora `self.a` vale 3 entonces `metodo` en B retorna 4 y por tanto C retorna 7. Me explico?

**Comment by nmaturana97** [comment]
Prueba con esto y ve si cumple lo que quieres:
```

from abc import ABCMeta


class Base(metaclass=ABCMeta):
    def __init__(self):
        self.a = 1
    def metodo(self):
        pass

class A(Base):
    def __init__(self):
        super().__init__()
        self.a = 2
        
    def metodo(self):
        self.a += 1
        return  self.a
class B(Base):
    def __init__(self):
        super().__init__()
        self.a = 2
        
    def metodo(self):
        self.a += 1
        return self.a

class C(A, B):
    def metodo(self):
        a = A.metodo(self) + B.metodo(self)
        return a

c = C()
print(c.metodo())
```

**Comment by naquiroz** [comment]
Funciona a la perfeccion, gracias!
