### ISSUE TITLE
Error con flake8

### ISSUE THREAD

**Issue by benjastraub** [IIC2233/Syllabus#13]
Estoy tratando de configurar Atom, pero tengo un problema con flake8. Cuando ocupo `pip install flake8` me arroja este error:

`Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pycodestyle.py'`

No entiendo por qué está relacionado con Python 2.7 si mi PATH es `/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}`

¿Qué puedo hacer para solucionarlo?

**Comment by vijuarez** [comment]
Hola!

Que sistema operativo estas utilizando?. A primera instancia te puedo recomendar:

- Puede ser que tengas instalado pip y pip3 (uno para cada versión) instalados al mismo tiempo. Intentalo con `pip3 install flake8` a ver si te soluciona el problema.

- Los errores de `Permission denied`, valga la redundancia, normalmente se soluciona dando más permisos. Si estas en windows, intentalo desde una ventana de comando como administrador. Si estas en linux, agregale `sudo` al comienzo del comando. No estoy seguro de como se da permisos de administrador en mac, eso si.

Nos cuentas como te va!

**Comment by benjastraub** [comment]
@vijuarez me funcionó usando `pip3` :smile: Muchas gracias!

**Comment by vijuarez** [comment]
De nada 😉
