### ISSUE TITLE
Problema en ACT1 test_recorrer_FaitHibrido

### ISSUE THREAD

**Issue by vichovargas** [IIC2233/Syllabus#149]
Hola al correr los test me sale este error:
Traceback (most recent call last):
  File "C:\Users\vicen\OneDrive\Escritorio\uc\9no semestre\progra avanzada\vichovargas-iic2233-2024-1\Actividades\AC1\test.py", line 420, in test_recorrer_FaitHibrido
    self.assertIn(res, ['Anduve por 5.0Km y gaste 5W de energia electrica Anduve por 5.0Km y gaste 5L de bencina',
AssertionError: 'Anduve por 5Km y gaste 5L de bencina Anduve por 5Km y gaste 5W de energia electrica' not found in ['Anduve por 5.0Km y gaste 5W de energia electrica Anduve por 5.0Km y gaste 5L de bencina', 'Anduve por 5.0Km y gaste 5L de bencina Anduve por 5.0Km y gaste 5W de energia electrica']
sin embargo, cuando pongo el kilometraje en float me tira error en otros test. Es un error del test o es un error mio? gracias

**Comment by martincortes21** [comment]
Me pasa lo mismo

**Comment by nicolettadegoye** [comment]
a mi igual :(

**Comment by xDani2024** [comment]
a mi también :(

**Comment by tnar01** [comment]
Hola! A mi me corre bien el test, quizás si revisas cómo pasas el argumento de la función recorrer lo puedas solucionar

**Comment by elneitans** [comment]
Tengan cuidado con los int()...

**Comment by vaniaulloa** [comment]
> Hola al correr los test me sale este error:
> Traceback (most recent call last):
>   File "C:\Users\vicen\OneDrive\Escritorio\uc\9no semestre\progra avanzada\vichovargas-iic2233-2024-1\Actividades\AC1\test.py", line 420, in test_recorrer_FaitHibrido
>     self.assertIn(res, ['Anduve por 5.0Km y gaste 5W de energia electrica Anduve por 5.0Km y gaste 5L de bencina',
> AssertionError: 'Anduve por 5Km y gaste 5L de bencina Anduve por 5Km y gaste 5W de energia electrica' not found in ['Anduve por 5.0Km y gaste 5W de energia electrica Anduve por 5.0Km y gaste 5L de bencina', 'Anduve por 5.0Km y gaste 5L de bencina Anduve por 5.0Km y gaste 5W de energia electrica']
> sin embargo, cuando pongo el kilometraje en float me tira error en otros test. Es un error del test o es un error mio? gracias
> 

Pudiste solucionarlo? Me pasa lo mismo :(

**Comment by nicolettadegoye** [comment]
El problema es que la función autobencina y autoelecrico pide retornar el numero de manera int(5Km) y los test case tienen la respuerta sin el int. ['Anduve por 5.0Km y gaste 5W de energia electrica Anduve por 5.0Km y gaste 5L de bencina']. alguien lo pudo solucionar?
