### ISSUE TITLE
Error de ultimo minuto

### ISSUE THREAD

**Issue by bvallejo1** [IIC2233/syllabus#163]
Hice las ultimas modificaciones de mi código y traspase algunas lineas de un archivo a otro, y ahora que lo corro después de un tiempo me tira el error MemoryError, como se arregla?

**Comment by jeschuwirth** [comment]
Ese error ocurre principalmente cuando te quedas sin RAM ejecutando el código, el primer comentario del siguiente link lo explica:

https://stackoverflow.com/questions/5537618/memory-errors-and-list-limits

No hay una forma exacta de solucionarlo, pero si explicas un poco los cambios que hiciste o revisas las lineas donde te levanta el error quizas puedas ayudarte.

**Comment by bvallejo1** [comment]
Hice cambios agregue un par de funciones y métodos a las clases, el error salta en un método de mi clase CentroUrbano especificamente crear_trabajador que lo unico que hace es instanciar un Trabajador y lo appendea a una lista, esto funcionaba perfecto hace unas horas.
Si lo subo a mi repositorio ustedes podran correrlo para revisarlo? es solo un problema de mi pc?

**Comment by jeschuwirth** [comment]
Si lo podemos ver, súbelo e intentaré ayudarte

**Comment by bvallejo1** [comment]
Lo subo a mi repositorio?

**Comment by jeschuwirth** [comment]
si

**Comment by bvallejo1** [comment]
esta subido

**Comment by jeschuwirth** [comment]
no me lanza memory error, pero si 
 'Civilizacion_t' object has no attribute 'puntos_de_tecnología'

**Comment by bvallejo1** [comment]
en que linea?

**Comment by bvallejo1** [comment]
Muchas gracias igualmente

**Comment by jeschuwirth** [comment]
Traceback (most recent call last):
  File "C:\Users\jschu\Desktop\PUC\2019\bvallejo1-iic2233-2019-1\Tareas\T01\main.py", line 275, in <module>
    lista = nueva_partida(info_civilizaciones, info_edificios)
  File "C:\Users\jschu\Desktop\PUC\2019\bvallejo1-iic2233-2019-1\Tareas\T01\main.py", line 16, in nueva_partida
    "DCC", info_edificios)
  File "C:\Users\jschu\Desktop\PUC\2019\bvallejo1-iic2233-2019-1\Tareas\T01\funciones.py", line 9, in crear_civilizacion
    civilizacion = c.DCC(info_civilizacion)
  File "C:\Users\jschu\Desktop\PUC\2019\bvallejo1-iic2233-2019-1\Tareas\T01\clases.py", line 90, in __init__
    super().__init__(info_civilizacion, tipo)
  File "C:\Users\jschu\Desktop\PUC\2019\bvallejo1-iic2233-2019-1\Tareas\T01\clases.py", line 23, in __init__
    self.puntos_de_tecnologia = civilizacion.puntos_de_tecnología
AttributeError: 'Civilizacion_t' object has no attribute 'puntos_de_tecnología'

**Comment by jeschuwirth** [comment]
el Error anterior es un problema de tilde en esa línea, pero luego de arreglarlo me aparece el siguiente error

Traceback (most recent call last):
  File "C:\Users\jschu\Desktop\PUC\2019\bvallejo1-iic2233-2019-1\Tareas\T01\main.py", line 275, in <module>
    lista = nueva_partida(info_civilizaciones, info_edificios)
  File "C:\Users\jschu\Desktop\PUC\2019\bvallejo1-iic2233-2019-1\Tareas\T01\main.py", line 22, in nueva_partida
    "Comarca", info_edificios)
  File "C:\Users\jschu\Desktop\PUC\2019\bvallejo1-iic2233-2019-1\Tareas\T01\funciones.py", line 24, in crear_civilizacion
    centro_urbano = c.CentroUrbano(info_edificios)
  File "C:\Users\jschu\Desktop\PUC\2019\bvallejo1-iic2233-2019-1\Tareas\T01\clases.py", line 279, in __init__
    super().__init__(info_edificios, nombre)
  File "C:\Users\jschu\Desktop\PUC\2019\bvallejo1-iic2233-2019-1\Tareas\T01\clases.py", line 252, in __init__
    edificio = info_edificios[nombre]
KeyError: 'centro_urbano'

**Comment by bvallejo1** [comment]
Me parece muy extraño ya que eso mismo funcionaba sin problemas en la mañana. Muchas gracias por la disposición

**Comment by jeschuwirth** [comment]
ningún problema, voy a estar mas o menos pendiente de esta issue, si necesitas ayudas o logras solucionarlo comenta :)

**Comment by bvallejo1** [comment]
ok gracias.

**Comment by gatochico** [comment]
Hola, un pequeño consejo!

Si logras solucionar ese error que ocurre y te das cuenta que no es algo díficil de arreglar, podrías agregar los pasos necesarios para solucionarlo en tu README. Así le ahorras tiempo al ayudante que te revise y puede que este implemente dicho arreglo y no te haga un descuento tan grande. Saludos!
