### ISSUE TITLE
Problema importando Paquetes  de PyQt5 en Python 3.6 en Ubuntu

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#235]
Hola, mi oroblema es que, pese a que haya instalado todo, me funciona importar PyQt5 pero me tira el lsiguiente error al intentar importar 

```python
import PyQt5.QtWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.QtWidgets'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.QtWidgets'
```

Buscque en google sin respuesta especifica a mi problema. 
En python3 si me funciona, el problema es solo en python3.6

Halp!

**Comment by andresfdezc** [comment]
Por ahora te aviso que en ubuntu no hay problema con que uses Python 3.5, ya que esta es la última versión soportada en ese sistema operativo.

**Comment by Kitaps** [comment]
.-. see algo así caxe
Es decir igual me funciona el 3.6 con unas maniobras que encontre en google pero para esto del PyQt5 no encontre como hacerlo.

Graicas

**Comment by fgbruna** [comment]
@Kitaps Que te corra con `python3` significa que PyQt5 está instalado en la versión de Python asociada al comando `python3`, y probablemente cualquier otra librería que hayas instalado previamente estén en la carpeta de esa versión.Si es que no te diste por vencido :sweat_smile: y te interesa instalarlas para  python3.6 exactamente te recomiendo usar:
`python3.6 -m pip install <nombre-paquete>`
