### ISSUE TITLE
Problema Instalación Jupyter (Windows)

### ISSUE THREAD

**Issue by sebastian-pena** [IIC2233/syllabus#29]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema Instalación Jupyter (Windows)

Hola! Descargué python 3.7.8, lo añadí al PATH, pero al momento de querer instalar jupyter me indica el siguiente error:
![Error Instalación jupyter](https://user-images.githubusercontent.com/69520559/112199454-f42c0380-8bec-11eb-9297-bea166c961a4.png)
Al tratar de ejecutar el comando en la terminal "jupyter notebook" me tira el arroja el siguiente error : "jupyter" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Por último, al tratar de abrirlo con un comando que me envió un ayudante, me aparece este error:
![image](https://user-images.githubusercontent.com/69520559/112200922-7cf76f00-8bee-11eb-9f64-11af3ab52ce5.png)

Perdón lo largo, pero es una issue muy específica, he tratado con múltiples soluciones que aparecen en internet y ninguna funciona:( Muchas gracias por leer:)

**Comment by IgnaciaJ** [comment]
Hola Sebastián! intenta usar el comando “python3 -m pip install jupyter" te dejo un hilo de stackoverflow donde puedes ver otras formas de instalación: https://stackoverflow.com/questions/48849385/cannot-install-jupyter-notebook/49665794

**Comment by sebastian-pena** [comment]
Hola Ignacia, ya había intentado los métodos que mencionaste y muchos más, ya no sé qué hacer:( La verdad es que hasta he pensado en desinstalar python y todas sus librerías, ya que de verdad he intentado muchas cosas y nada funciona:(

**Comment by aaossa** [comment]
Hola @sebastian-pena , ¿podrías mostrar el *output* de los siguientes comandos?

* `python --version`
* `pip --version`
* `pip show jupyter`
* `pip show zmq`

Además, ¿cómo instalaste Python (en particular, pregunto por si tienes Anaconda).

**Comment by sebastian-pena** [comment]
Hola profesor, muchas gracias por ayudarme con la issue :)
Para no hacer más extenso el screenshot, no puse el output de python --version, pero tengo instalada la version 3.7.8
![Screenshot_1](https://user-images.githubusercontent.com/69520559/112235179-e0989100-8c1c-11eb-84c5-418df9183f9a.png)
Por último, lo instalé con el ejecutable oficial de python, nunca he instalado anaconda en mi computador.
Reiterar mis agradecimientos profe 🤲

**Comment by aaossa** [comment]
¿Podrías mostrarme el *output* del comando `pip show pyzmq` porfa?

**Comment by sebastian-pena** [comment]
Ahí está profesor
![pyzmq](https://user-images.githubusercontent.com/69520559/112237200-f1e39c80-8c20-11eb-9935-182e879c1131.png)

**Comment by aaossa** [comment]
Mmm, veamos cómo te va con esto, vamos a reinstalar `zmq`:

1. `pip uninstall pyzmq`
2. `pip install pyzmq`

Después intenta ejecutar `python -m jupyter notebook`. El comando sería solo `jupyter notebook` normalmente, pero no tienes Python instalado en el PATH (si usaste el instalador ejecutable para Windows, hay una cajita abajo en la ventane en un momento que te permite agregarlo, por si reinstalas Python).

**Comment by sebastian-pena** [comment]
El primer comando funcionó profe, ahora sí puedo abrir Jupyter, muchas gracias 😄. No sé qué habrá pasado, porque sí instalé python añadiendo el path, pero por ahora no me genera mayor problema (ni espero lo haga). Ahora sí podré revisar las clases, muchas gracias por responder 😄

**Comment by sebastian-pena** [comment]
Soy yo de nuevo, perdón. Ahora que tuve tiempo, intenté correr las celdas, pero me aparece un recuadro rojo que dice "Kernel error", esto es lo que me dice:
Traceback (most recent call last):
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 111, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "C:\Users\sebac\AppData\Roaming\Python\Python37\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
  File "C:\Users\sebac\AppData\Roaming\Python\Python37\site-packages\jupyter_client\manager.py", line 309, in start_kernel
  File "C:\Users\sebac\AppData\Roaming\Python\Python37\site-packages\jupyter_client\manager.py", line 256, in pre_start_kernel
  File "C:\Users\sebac\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 474, in write_connection_file
  File "C:\Users\sebac\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
  File "c:\users\sebac\appdata\local\programs\python\python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\sebac\AppData\Roaming\Python\Python37\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\sebac\AppData\Roaming\Python\Python37\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: %1 no es una aplicación Win32 válida.

**Comment by dfloreaa** [comment]
Hola! Según internet suele arreglarse al correr ``pip install --upgrade pywin32``, ojalá sirva ☺ (si no ignorenme jeje)

**Comment by sebastian-pena** [comment]
Hola! Lo acabo de arreglar utilizando ` pip uninstall pywin32` y luego ` pip install pywin32` , por si a alguien le sirve 😃
