### ISSUE TITLE
error: metadata-generation-failed descargando PyQt5 Mac M1

### ISSUE THREAD

**Issue by Fixer575** [IIC2233/Syllabus#3]
Hola!
Me salta este error al instalar PyQt5 en Mac M1, no logré encontrar la solución en internet:
Collecting PyQt5==5.14.1
  Downloading PyQt5-5.14.1.tar.gz (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 3.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/5_/1w_blvws1dvfmd6m8_81gpyh0000gn/T/pip-build-env-fkgorv_t/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "/private/var/folders/5_/1w_blvws1dvfmd6m8_81gpyh0000gn/T/pip-build-env-fkgorv_t/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/5_/1w_blvws1dvfmd6m8_81gpyh0000gn/T/pip-build-env-fkgorv_t/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 479, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/5_/1w_blvws1dvfmd6m8_81gpyh0000gn/T/pip-install-oyivv_wc/pyqt5_d54349f98e5b4d198e5a09bd0278cfa2/project.py", line 62, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/5_/1w_blvws1dvfmd6m8_81gpyh0000gn/T/pip-build-env-fkgorv_t/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/5_/1w_blvws1dvfmd6m8_81gpyh0000gn/T/pip-build-env-fkgorv_t/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 225, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/5_/1w_blvws1dvfmd6m8_81gpyh0000gn/T/pip-build-env-fkgorv_t/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Hernan4444** [comment]
Hola @Fixer575 

Para confirmar, ¿seguiste el tutorial de aquí https://github.com/IIC2233/Syllabus/wiki/5.-PyQt5-para-Mac-con-M1  para activar Rosetta? que ese error recuerdo que salía porque con M1 se necesita usar una terminal que tenga Rosetta.

Confirmanos esa información para pensar en más alternativas que puedan solucionar tu problema c:

Quedamos atentos,

**Comment by Fixer575** [comment]
Hola @Hernan4444, 
Sí, lo había visto pero esté ya no funciona porque con la última actualización de Ventura ya no se puede copiar y pegar una nueva Terminal. No obstante un amigo me ayudó y ya logré instalarlo. 
Gracias de todas maneras!

**Comment by rafarencoretg** [comment]
tengo el mismo error pero en windows

**Comment by Hernan4444** [comment]
Hola @rafarencoretg 

Puedes subir el error completo que te sale, para poder ver el log y tener alguna pista de dicho error.

Quedamos atentos,

**Comment by rafarencoretg** [comment]
![image](https://user-images.githubusercontent.com/74164604/224189874-b586b6ba-2662-40b2-bb85-4c0ea8e9c0eb.png)
![image](https://user-images.githubusercontent.com/74164604/224189910-2a32d893-5f33-4028-be8e-9b4c66ac02e5.png)

**Comment by Hernan4444** [comment]
Hola @rafarencoretg 

Ojo que ahí estás haciendo install de `pyqt5-tools`, pero en la guía de la.wiki no se pide hacer esobpara Windows. Sino que les entregamos un link para instalar qtdesigner 😃

Saludos c:

**Comment by terecarvallo** [comment]
Hola @Fixer575 
Podrias decir como lo hiciste con un mac M1? Que tampoco pude clonar el terminal. Lo otro que me pasa cuando escribo python --version en el terminal me tira error por si alguien sabe que estoy haciendo mal 

Gracias!!

**Comment by Hernan4444** [comment]
Para complementar la respuesta anterior, hay una segunda solución:

Esta consiste en hacer uso de un terminal externo, iTerm, y ejecutar éste utilizando Rosetta para poder emular x86 y no ARM. Para esto, se descarga esta terminal de https://iterm2.com/

Una vez instalado, ir a "Aplicaciones" y buscar `iter2` en esa lista. Hacer *click derecho* e ir a `Obtener información`, acá una ventana donde debes asegurarte que la casilla `Abrir con Rosetta` esté marcada.

Con esto tendras 2 terminal: `terminal` e `iterm 2`. La primera no tendrá rosetta y no podrás usar PyQt5. La segunda si tendrá rosetta y podrás instalar y utilizar pyqt5 sin problema.

Si la primera solución no te funciona o no te gustó por esos comandos que pueden asustar un poco, y decides probar con esta, cuentanos como te va c:

**Comment by Fixer575** [comment]
@terecarvallo 
Mi amigo me dijo que con esto lo hizo https://vineethbharadwaj.medium.com/m1-mac-switching-terminal-between-x86-64-and-arm64-e45f324184d9. Si no me equivoco es lo mismo que comentó @Hernan4444. 
Y para ver tu versión de python prueba con "python3 -V", a mi me funciona con eso.

**Comment by josegarafulic** [comment]
Hola @Hernan4444 , quería saber si es que se puede ocupar PyQt6 que es compatible con los macbook pro M1, o habría problemas?

**Comment by Hernan4444** [comment]
Hola, 

No se puede trabajar con la 6, debe ser la versión 5 que es la oficial del curso.

Sobre la segunda pregunta, entiendo que por defecto, la terminal siempre se abrirá en arm64 y hay que hacer el switch a i386 una vez abierta la terminal.

Saludos!

**Comment by franfonte** [comment]
<img width="1308" alt="Error" src="https://user-images.githubusercontent.com/111889435/234358740-2e384097-34e1-479c-805d-46fc57e4335c.png">

**Comment by Hernan4444** [comment]
Hola @franfonte 

¿Puedes darnos más información de qué computador tienes? (qué versión de mac (ventura, catalina, etc) y chip )m1, intel o m2))

Por otro lado, tal vez se me ocurre instalar PyQt5 desde _homebrew_ aprovechando que lo tienes instalado: https://formulae.brew.sh/formula/pyqt@5

Sino, lo que más se me ocurre que pudo haber pasado, es que Instalaste Python desde homebrew, pero homebrew no acepta PyQt5. Por lo tanto, una opción sería eliminar el Python de Homebrew (`brew uninstall python@3.10`) y instalar python como un programa externo 

1. Ir aquí https://www.python.org/downloads/release/python-31011/, bajar en la página y seleccionar [macOS 64-bit universal2 installer](https://www.python.org/ftp/python/3.10.11/python-3.10.11-macos11.pkg)
2. Instalarlo como si fuera una aplicación externa (doble click en al archivo .pkg que descargues)
3. Luego instalar PyQt5 cómo se explica anteriormente (activar rosetta mediante otra terminar y haciendo el switch, y luego `pip3 install PyQt5`).
 
Cuantanos como te va con ello,
Saludos!

**Comment by franfonte** [comment]
MacOs: Ventura 13.3.1
Chip: Apple m1 pro
voy a tratar lo de python y te aviso

**Comment by franfonte** [comment]
<img width="565" alt="Captura de pantalla 2023-04-25 a la(s) 18 40 01" src="https://user-images.githubusercontent.com/111889435/234419482-c333cb16-9996-4f5a-b08e-9ff708c979ca.png">
Creo que ahi funciono, muchas gracias. ¿De casualidad sabes como puedo hacer que mi terminal predeterminado de VSC sea    el terminal de Iterm2?

**Comment by Hernan4444** [comment]
Hola, 

Ahí me mataste jajajaj que yo ocupo la terminal externa y no la de VSCode, pero te dejo esta respuesta de stackoverflow donde hablan de eso (No puedo prometer que funcione porque nunca lo he hecho, yo soy fiel creyente de terminal externa a la de VSCode jajajaj)

Saludos!
