### ISSUE TITLE
Error thread del cliente en thread_escuchar()

### ISSUE THREAD

**Issue by diegocostares** [IIC2233/Syllabus#308]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/293)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola en el horario de ayudantía de hoy intente arreglar un error que me ocurre con los thread al cerrar el cliente pero no hubo tiempo para solucionarlo, adjunto el error que me aparece en consola. Mi función de escuchar() es prácticamente igual a la AF4. 
_PD: El error me ocurre con daemon=True o False... sospecho que tiene que ver con algun args_

```
Conexión terminada.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/diegocosta/Downloads/Programacion/diegocostares-iic2233-2021-2/Tareas/T3/cliente/clientee.py", line 50, in thread_escuchar
```

**Comment by diegocostares** [comment]
Lo terminé solucionando creando un atributo self.conectado que parte en True y se cambia a False al salir. Por lo que en vez de hacer "while True", hice que hiciera "while self.conectado:".

Lo comento por si a alguien también le sirve 🖌️

**Comment by diegocostares** [comment]
Hola, he vuelto a tener este problema, tengo una función que se encarga de hacerle .close al socket de mi cliente, pero cuando llamo ejecuto envió una señal para ejecutar esta función desde mi closeEvent de las diferentes ventanas me arroja un error. Antes habia solucionado mi problema creando una variable llamada self.cliente_conectado y lo remplazaba por el while True, pero ahora sigue intentando ejecutar los Thread y no entiendo por qué...
```
--- Conexión terminada ---

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/diegocosta/Downloads/Programacion/diegocostares-iic2233-2021-2/Tareas/T3/cliente/clientee.py", line 49, in thread_escuchar
    mensaje = self.recibir()
  File "/Users/diegocosta/Downloads/Programacion/diegocostares-iic2233-2021-2/Tareas/T3/cliente/clientee.py", line 64, in recibir
    self.socket_cliente.recv(4), byteorder='little')
OSError: [Errno 9] Bad file descriptor
```
