### ISSUE TITLE
Duda en error importación archivo .ui tarea 2 (plazo extra)

### ISSUE THREAD

**Issue by AaronPantoja** [IIC2233/Syllabus#317]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, tengo una duda sobre un error que me aparece al tratar correr el código. Me aparece en la parte del frontend de la ventana de juego y es el siguiente error que no logro descifrar:

PS C:\Users\ap7on\Desktop\progra av\AaronPantoja-iic2233-2022-2\Tareas\T2> & C:/Users/ap7on/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/ap7on/Desktop/progra av/AaronPantoja-iic2233-2022-2/Tareas/T2/front_vent_juego.py"
Traceback (most recent call last):
File "c:\Users\ap7on\Desktop\progra av\AaronPantoja-iic2233-2022-2\Tareas\T2\front_vent_juego.py", line 7, in
window_name, window_class = uic.loadUiType("ventana_juego.ui")
File "C:\Users\ap7on\AppData\Local\Programs\Python\Python310\lib\site-packages\PyQt5\uic_init_.py", line 204, in loadUiType
exec(code_string.getvalue(), ui_globals)
File "", line 141, in
ModuleNotFoundError: No module named 'fondo_rc'

Es raro, porque cambio el nombre del archivo (a por ejemplo el de la ventana de inicio) cuando hago uic.loadUiType y desaparece el error. También intente meterme al archivo .ui a través de visual studio y el error que me aparece en la línea indicada, no estaba. Además, nunca definí nada llamado fondo_rc, solo tengo un label con nombre fondo.
No puedo seguir avanzando en mi tarea (tengo plazo extra) si no puedo correr el código.

**Comment by Hellonston** [comment]
Hola **AaronPantoja**!  quizá esto te puede servir: https://stackoverflow.com/questions/41301204/importerror-no-module-named-resource-rc
Es probable que en ventana inicio no tengas nada relacionado con rc y solo lo ocupes en ventana juego, por esa razón funciona en una y en otra no, otra cosa es que intentes hacer un push de prueba ahora ya que quizá te salga un error por el .qrc más que nada para que cerca de la hora de entrega hayas solucionado potenciales errores.
Cuéntame que tal te va!

**Comment by AaronPantoja** [comment]
Ahí lo arregle, el problema es que había puesto una foto en .qrc pero después la había sacado, pero se me quedo en el código .ui así que tuve que borrar una línea que decía sobre eso y se arregló
