### ISSUE TITLE
No funciona Networking -- Error: WinError 10038

### ISSUE THREAD

**Issue by jsilvalavin** [IIC2233/Syllabus#342]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/293)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Estaba tratando de hacer el código de la ayudantía de Networking. Copiando literalmente el mismo código, me sale el siguiente error en la consola:

Traceback (most recent call last):
  File "c:/Users/Maria Ignacia/Desktop/Intento/servidor/servidor.py", line 13, in <module>
    socket_cliente, address = socket_servidor.accept()
  File "C:\Users\Maria Ignacia\AppData\Local\Programs\Python\Python38\lib\socket.py", line 292, in accept
    fd, addr = self._accept()
OSError: [WinError 10038] Se intentó realizar una operación en un elemento que no es un socket
PS C:\Users\Maria Ignacia\Desktop\Intento\servidor>

Pareciera ser un error de la libreria o algo así! No puedo avanzar en la tarea con esto :(

**Comment by tocococa** [comment]
Hola @jsilvalavin , lo más probable que está ocurriendo es que `socket_servidor` no es un socket, o solo está declarado como `socket()` y falta pasarle los argumentos `socket.AF_INET, socket.SOCK_STREAM` o `socket.AF_INET, socket.SOCK_DGRAM` para inicializarlo.

**Comment by jsilvalavin** [comment]
> Hola @jsilvalavin , lo más probable que está ocurriendo es que `socket_servidor` no es un socket, o solo está declarado como `socket()` y falta pasarle los argumentos `socket.AF_INET, socket.SOCK_STREAM` o `socket.AF_INET, socket.SOCK_DGRAM` para inicializarlo.

hola @tocococa gracias :) Pero si lo defini como dices, **copie al pie de la letra el codigo de la ayudantía**, es decir el de estos pantallazos:

El servidor
![image](https://user-images.githubusercontent.com/89276993/145254094-88c0ac59-ae8b-4837-a310-b93f6b5cc27c.png)

El cliente
![image](https://user-images.githubusercontent.com/89276993/145254094-88c0ac59-ae8b-4837-a310-b93f6b5cc27c.png)

Además, note que el error tiene un traceback a la libreria socket, al parecer :( Que podría ser en este caso?

**Comment by try-except** [comment]
Es por el `finally`, estás cerrando la conexión en cada vuelta del `while`

**Comment by jsilvalavin** [comment]
> A mi me pasaba exactamente el mismo error cuando intentaba introducir los datos del inicio por segunda vez, después de un buen rato a lo único que llegué y que solucionó el problema fue establecer de nuevo la conexión antes de enviar los datos al servidor. Por si acaso, no sé realmente si es lo ideal, pero es lo que me ayudo a solucionarlo.

veré eso, gracias!

**Comment by jsilvalavin** [comment]
> Es por el `finally`, estás cerrando la conexión en cada vuelta del `while`. Una vez se cierra un `socket` ya no se puede reutilizar.
> 
> Además creo que subiste la misma foto para el cliente y el servidor?

aah, entonces cuando debo cerrar el socket del servidor? mencionaron que debia hacerse
y sí, tienes razon ahi arregle las fotos jaja

**Comment by jsilvalavin** [comment]
> Puedes cerrar el `socket` del servidor cuando quieras, el problema es que en este snippet en específico tienes:
> 
> ```python
> while True:
>     try:
>         socket_cliente, address = socket_servidor.accept()
>         ...
>     except:
>          ...
>     finally:
>         socket_servidor.close()
> ```
> 
> Entonces en la primera vuelta del `while` cierras el `socket` y luego en la segunda vuelta intentas hacer `accept`, pero como el `socket` ya está cerrado te tira ese error. A lo mejor tendrías que ver cuándo salir del `while` y una vez fuera cerrar el `socket`

Ya bacan, gracias!! Te pasaste en serio...
Porfin voy a poder partir armando el mono :)
