### ISSUE TITLE
error consultas.json al leer la 7ma y 8va consulta

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#346]
Hola, me arroja un error en eso. ¿Es problema del archivo que subieron?

**Comment by Arcoirisky** [comment]
¿Puedes explicar un poco el error?

**Comment by nmaturana97** [comment]
Es probando el archivo que uds subieron: consultas.json.
Pruebo la 7ma u 8va consulta (por separado, juntas, o todas) y me arroja este error:

Traceback (most recent call last):
  File "C:\Users\Nicolas Maturana\Desktop\Universidad\semestre 4\Programacion Avanzada\T03\gui\Gui.py", line 107, in process_query
    array.append(json.loads(querry.text().replace("'", '"')))
  File "C:\Users\Nicolas Maturana\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Nicolas Maturana\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Nicolas Maturana\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 18 (char 17)

**Comment by nmaturana97** [comment]
Me baje la actualizacion y ahora funciona, mis disculpas.

**Comment by Arcoirisky** [comment]
No pasa nada :)
