### ISSUE TITLE
Problema enviar datos entre cliente y servidor

### ISSUE THREAD

**Issue by Crisax234** [IIC2233/Syllabus#358]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/293)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola tengo una duda con mi código cuando quiero enviar datos al servidor una vez que el cliente ya se conecto, utilizo threads para escuchar lo que llegue al servidor por parte de un socket y viceversa, la primera vez que envió algo al servidor este me responde sin problemas, sin embargo cuando quiero enviar algo al servidor nuevamente de la misma forma, el servidor no recibe nada y tampoco me da ningun error, como si ya no fuera capaz de recibir mensajes por el cliente, como podría solucionarlo?

De antemano muchas gracias

**Comment by eliseolopez20** [comment]
Hola @Crisax234 
Si tu servidor solo puede recibir un mensaje y después no recibe, probablemente esta fallando el while true, dado que si no usas eso correctamente la función de recibir solo corre una vez y finaliza.
Quedo atento si no se soluciona el problema

**Comment by Crisax234** [comment]
Si lo pude solucionar y el servidor me escucha el mensaje, sin embargo me aparece este error: 

Exception in thread Thread-2:
Traceback (most recent call last):     
  File "C:\Users\crist\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner       
    self.run()
  File "C:\Users\crist\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\crist\Crisax234-iic2233-2021-2\Tareas\T3\servidor\servidor.py", line 84, in listen_client_thread    
    dict_recibido = json.loads(dict_comando.decode('utf-8'))
  File "C:\Users\crist\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)  
  File "C:\Users\crist\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 33 (char 32)

lo busque pero no entiendo muy bien qué significa en mi código, que puede estar provocándolo?

**Comment by eliseolopez20** [comment]
No logre encontrar el error, porque creo que no tienes tu repo personal actualizado. Sin embargo, encontre un par de respuestas en google que podrían ayudarte a encontrar el error, que podría ser por como esta definido tu archivo JSON [link1](https://stackoverflow.com/questions/21058935/python-json-loads-shows-valueerror-extra-data/51830719) y [link2](https://stackoverflow.com/questions/13675401/cant-read-json-file-in-python)

**Comment by Crisax234** [comment]
Perdon ahora lo acabo de actualizar, la cosa es que no es al cargar el archivo json, sin que cuando le hago un json.loads a un comando que envio

**Comment by eliseolopez20** [comment]
Revisando tu código, creo que el error esta en el tipo de dato de dict_comando de la función listen_thread en cliente.py. Te recomiendo usar print(type()) para ver que tipo de datos estas usando y si es el que quieres usar para poder manejar  el mensaje que deseas enviar. Recomiendo revisar los contenidos de la semana-11 que muestran como trabajar con los distintos tipos de datos.
Espero haberte ayudado

**Comment by Crisax234** [comment]
Ya entendí por que no funciona pero no logro decifrar por que el diccionario que quiero mandar se repite tantas veces cuando lo paso a bytes siendo que hago eso solo una vez :/

**Comment by Crisax234** [comment]
Ya lo pude resolver muchas gracias por tu tiempo!

**Comment by eliseolopez20** [comment]
Que bueno, mucho ánimo con lo que queda de semestre!
