### ISSUE TITLE
ASCII tildes

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#42]
al tratar de leer el archivo cdv con los usuarios la consola me dice lo siguiente:

```python
Traceback (most recent call last):
  File "/Users/Rodrigo/Desktop/2017/Progra Avanzada/Repositorio Git/Tareas/T01/users.py", line 98, in <module>
    f.readlines()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 237: ordinal not in range(128)
```

como se puede solucionar el formato ascii??

**Comment by IchottMano** [comment]
Intenta poniendo " encoding='utf-8' " en el comando que abre el archivo, ya que ASCII no reconoce las tildes, se vería mas o menos asi:
open(*archivo*, *modo*, encoding='utf-8')

**Comment by GustavPrudencio** [comment]
Una posible solución es llamar a la funcion open con argumento errors="ignore" o encoding="el encoding mas correcto para el archivo"
