### ISSUE TITLE
Error al crear instancia de una clase

### ISSUE THREAD

**Issue by iastruque** [IIC2233/syllabus#472]
Traceback (most recent call last):
  File "c:/Users/ignac/Desktop/iastruque-iic2233-2020-1/Tareas/T01/cargar.py", line 78, in <module>
    for i in leer_archivos_criaturas():
  File "c:/Users/ignac/Desktop/iastruque-iic2233-2020-1/Tareas/T01/cargar.py", line 33, in leer_archivos_criaturas
    int(criatura[8]), str(criatura[9]), str(criatura[10]), int(criatura[11]), int(criatura[12].strip('\n')))
  File "c:\Users\ignac\Desktop\iastruque-iic2233-2020-1\Tareas\T01\Entidades.py", line 145, in __init__
    super().__init__(self, nombre, nivel_mágico, probabilidad_de_escape, probabilidad_de_enfermarse, estado_de_salud, estado_escape, puntos_salud_total, puntos_salud_actual, nivel_de_hambre, nivel_de_agresividad, días_sin_comer, nivel_cleptomanía)       
TypeError: __init__() takes 13 positional arguments but 14 were given
PS C:\Users\ignac\Desktop\iastruque-iic2233-2020-1\Tareas\T01> 

Llevo un par de horas revisando mi código y no puedo encontrar el error que estoy cometiendo.
He revisado la sub clase, la super clase y la lista que estoy utilizando y veo que estoy dando la cantidad de parametros correctos. (aunque no es así)

Por favor ayuda

**Comment by KnowYourselves** [comment]
Hola @iastruque!

Lo que sucede es que la función `super` pasa la referencia a `self` por automáticamente, no es necesario que se la entregues.  Por lo tanto, al hacer `super().__init__(self, ....` estás pasando un argumento extra, lo que te dice el error es que la función recibe 13 argumentos pero le pasaste 14. Si borras ese `self` debería funcionar.

Éxito!
