### ISSUE TITLE
Error \chao al tratar de sacar a un usuario del chat

### ISSUE THREAD

**Issue by tomishishigang** [IIC2233/syllabus#492]
hola, 
para implementar el comando \chao, en el servidor reviso que se cumpla la condicion de la mitad mas un votantes. Luego si esta se cumple envio la info al cliente para terminar la conexion de este usuario y emitir una señal hacia el frontend para poder cerrar su ventana de chat. Esto funciona correctamente pero me tira el siguiente error de Thread:
```python
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/tomas/Desktop/Progra/tomishishigang-iic2233-2019-1/Tareas/T03/server/server.py", line 81, in escuchar_cliente_thread
    self.manejar_comando(decoded, client_socket)
  File "C:/Users/tomas/Desktop/Progra/tomishishigang-iic2233-2019-1/Tareas/T03/server/server.py", line 119, in manejar_comando
    for tuplas in self.sockets.items():
RuntimeError: dictionary changed size during iteration
```

El servidor y el cliente funcionan, el comando igual incluso luego de aparecer este error pero no logro solucionarlo, no se que podría ser. 
Saludos

**Comment by KnowYourselves** [comment]
Hola @tomishishigang!

Recomendación general: Los errores de Python son **muy descriptivos**, de hecho estan diseñados para ser leidos de atras para adelante.

Lo primero que te dice el error es:

> RunTimeError: dictionary changed size during iteration

Por lo cual el error esta claro, estas iterando un diccionario (`for tuplas in self. socket. items()`) y lo cambiaste durante el proceso, ergo el error. Esto quiere decir que debes buscar una forma de eliminar el usuario del dict que no sea durante la iteración. (O ver si existe otra opción.) 

Espero haberte ayudado!

**Comment by tomishishigang** [comment]
Hola, 
muchas gracias por la ayuda. Sorry la molestia pero me equivoque al copiar el error, el que no pude solucionar era el siguiente: 
```python
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/tomas/Desktop/Progra/tomishishigang-iic2233-2019-1/Tareas/T03/server/server.py", line 77, in escuchar_cliente_thread
    decoded = json.loads(response)
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python36\lib\json__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Trate de hacer un except para este error pero no me funciono, no se como solucionarlo. 
Saludos.

**Comment by KnowYourselves** [comment]
Antes de la linea 77 agrega `print(response) `, para ver que le estas pasando a `loads`, a veces ese error pasa cuando intentas hacer loads de slgo que no es un json.

Cuéntame que tal?

**Comment by Witomi** [comment]
A mi me pasa lo mismo y al parecer es porque response es un None....

**Comment by tomishishigang** [comment]
Al agregar un print(response, "aca se printea response") a la linea anterior a la 77 luego de agregar un cliente, mandar un mensaje "hola" y aplicar el comando \chao, justo antes del error me printea lo siguiente:
```python
{"status": "nuevo_usuario", "data": "tomas"} aca se printea response
Mensaje Recibidos: {'status': 'nuevo_usuario', 'data': 'tomas'}
{"status": "mensaje", "data": {"usuario": "tomas", "contenido": "hola"}} aca se printea response
Mensaje Recibidos: {'status': 'mensaje', 'data': {'usuario': 'tomas', 'contenido': 'hola'}}
{"status": "mensaje", "data": {"usuario": "tomas", "contenido": "\\chao tomas"}} aca se printea response
Mensaje Recibidos: {'status': 'mensaje', 'data': {'usuario': 'tomas', 'contenido': '\\chao tomas'}}
 aca se printea response
```
Efectivamente el error ocurre dado que response esta vacio

**Comment by tomishishigang** [comment]
Logre arreglar el error (creo) al hacer un except para ese caso. Muchas gracias por tu ayuda.
