### ISSUE TITLE
arrivals.csv

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#511]
Hola!
Al intentar abrir el archivo arrivals.csv con encoding=utf-8 me levanta el siguiente error:

```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 3481: invalid continuation byte
```
Al parecer es porque el día sábado tiene como carácter un punto en vez de una a con acento (á).

**Comment by Hernan4444** [comment]
Hola, acabo de subir un nuevo archivo con encoding UTF-8 ahora si lo abren con ese encoding, no deberían tener problemas.

Saludos ✌️
