### ISSUE TITLE
Error en lectura archivo posts.csv

### ISSUE THREAD

**Issue by jnbaltra** [IIC2233/syllabus#60]
Hola! Me aparece un error al momento de querer leer el archivo posts.csv
Traceback (most recent call last):
  File "C:/Users/Joaquin/Desktop/Universidad/Cuarto año/Primer Semestre/Programacion Avanzada/jnbaltra-iic2233-2020-1/Tareas/T00/Lector.py", line 20, in <module>
    lista_posts = leer_archivo(postsarch)
  File "C:/Users/Joaquin/Desktop/Universidad/Cuarto año/Primer Semestre/Programacion Avanzada/jnbaltra-iic2233-2020-1/Tareas/T00/Lector.py", line 7, in leer_archivo
    contenido = archivo.readlines()
  File "C:\Users\Joaquin\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1527: character maps to <undefined>

Me da la impresión que el error es que hay un caracter del archivo que no lo reconoce python, no se como ampliar los caracteres para que lo pueda reconocer python, vi que otro alumno tenía un error similar y le dijieron que el problema probablemente era el encode de open, a este yo le puse "r+". Quedo atento

**Comment by jnbaltra** [comment]
no sé como ponerle la etiqueta al issue :(

**Comment by KnowYourselves** [comment]
Hola @jnbaltra!

Esta pregunta ya fue respondida en #16. Recuerda revisar el compilado de issues antes de preguntar.

PD: Respecto a las etiquetas no te preocupes, los ayudantes las etiquetamos!

Éxito!
