### ISSUE TITLE
Semana 8 - Error al final de la ejecución del ejercicio 2.1 y 2.2

### ISSUE THREAD

**Issue by CatalinaGoldsack** [IIC2233/syllabus#629]
Hola! Al hacer correr los ejercicios me funcionan perfecto los threads hasta que al final me lanza este error:
Traceback (most recent call last):
  File "/Users/CatalinaGoldsackPerez/Documents/Ingenieria Civil/VII Semestre/Programacion Avanzada/ejercicios_semana_8/ejercicio_2.2.py", line 37, in <module>
    n4.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 848, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once

**Comment by fdoflorenzano** [comment]
¡Hola @CatalinaGoldsack!

El error sugiere que existe algún *thread* en tu código que se le llama `start` más de una vez. (Específicamente el error muestra que es en una línea: ` n4.start()` en `ejercicio_2.2.py`). Revisa si no pudiste un `start` demás.

Espero te ayude, nos avisas cualquier cosa.
Saludos.

PD: Viendo la ruta de tus archivos, veo que los tienes muy organizados para ejercitar cada ejercicio en un archivo por separado. ¡Qué bueno! 😄

**Comment by CatalinaGoldsack** [comment]
Jajajaja era eso!!! no me había dado cuenta! muchas gracias! :)
