### ISSUE TITLE
Problemas al importar módulos de PyQt5 (Varias versiones de python)

### ISSUE THREAD

**Issue by ljgonzalez1** [IIC2233/syllabus#674]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Datos Sistema

OS: KDE Neon 5.19 (Basado en Ubuntu 20.04)
Kernel: Linux 5.4.0-48-generic

### Problema

Hace un tiempo, por otro ramo, tuve que usar Python 3.5 para poder correr un código. De alguna forma que no recuerdo quedó como la versión principal en mi PC. PyQt5 me funciona desde ahí, temo que puedan haber incompatibilidades o errores de algún tipo si programo con esa versión.

```
  ╭──luis at GL753VD in ~
  ╰─○ python3                                                                   
Python 3.5.10 (default, Sep  8 2020, 23:19:44) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
>>> from PyQt5 import QtWidgets
>>> quit()
```

Para este ramo, uso Python 3.7.9. Si ejecuto desde el terminal, lo llamo con `python3.7`. Como IDE uso PyCharm con Python 3.7.9 configurado por defecto.

Espero que sea más de utilidad que una molestia que describa todo lo que hice:
Primero, actualicé pip:
```
  ╭──luis at GL753VD in ~
  ╰─○ python3.7 -m pip install --upgrade pip                                                                                                                   
Defaulting to user installation because normal site-packages is not writeable
Collecting pip
  Using cached pip-20.2.3-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-20.2.3
```

Luego, instalé las librerías:
```
  ╭──luis at GL753VD in ~
  ╰─○ python3.7 -m pip install pyqt5 pyqt5-tools                                                                                                                        
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyqt5 in /usr/lib/python3/dist-packages (5.15.1)
Collecting pyqt5-tools
  Downloading pyqt5_tools-5.15.1.1.7.5-cp37-cp37m-manylinux2014_x86_64.whl (83.3 MB)
     |████████████████████████████████| 83.3 MB 2.02 MB/s 
Requirement already satisfied: PyQt5-sip<13,>=12.8 in ./.local/lib/python3.7/site-packages (from pyqt5) (12.8.1)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from pyqt5-tools) (7.0)
Collecting python-dotenv
  Using cached python_dotenv-0.14.0-py2.py3-none-any.whl (17 kB)
Installing collected packages: python-dotenv, pyqt5-tools
Successfully installed pyqt5-tools-5.15.1.1.7.5 python-dotenv-0.14.0
```

Para probar que todo haya funcionado quise probar desde el terminal:
```
  ╭──luis at GL753VD in ~
  ╰─○ python3.7                                                                                                                                                         
Python 3.7.9 (default, Aug 18 2020, 02:07:21) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
>>> 
>>> quit()
```
(Funcionó)

Corrí los códigos de ejemplo y tenía problemas con distintos módulos de PyQt5, así que importé uno solo desde el terminal para ver qué pasaba:
```
  ╭──luis at GL753VD in ~
  ╰─○ python3.7                                                                                                       
Python 3.7.9 (default, Aug 18 2020, 02:07:21) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import QtWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'QtWidgets'
>>> quit()
```
(No funcionó)

Busqué en Google, no me ayudó mucho. Jugué un poco con los archivos, terminé por copiar los archivos de los módulos de la librería directo en la carpeta de PyQt5 y (creo que) avancé un poco.
```
  ╭──luis at GL753VD in ~
  ╰─○ python3.7                                                                                                       
Python 3.7.9 (default, Aug 18 2020, 02:07:21) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import QtWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip'
>>> quit()
```
(El error es distinto, supongo que la librería hace referencia a un archivo `PyQt5.sip` que no encontró a pesar de que copié todos los archivos varias veces por si acaso)

Luego decidí borrar todo y volver a intentar instalar. En una de esas funcionaba.
```
  ╭──luis at GL753VD in ~
  ╰─○ python3.7 -m pip uninstall pyqt5 pyqt5-tools                             1 ↵
Found existing installation: PyQt5 5.15.1
Uninstalling PyQt5-5.15.1:
  Would remove:
    /home/luis/.local/bin/pylupdate5
    /home/luis/.local/bin/pyrcc5
    /home/luis/.local/bin/pyuic5
    ...
    (MUCHAS LÍNEAS)
    ...
    /home/luis/.local/lib/python3.7/site-packages/pyqt5_tools/*
Proceed (y/n)? y
  Successfully uninstalled pyqt5-tools-5.15.1.1.7.5

  ╭──luis at GL753VD in ~
  ╰─○ python3.7 -m pip install pyqt5 pyqt5-tools                                  
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyqt5 in ./.local/lib/python3.7/site-packages (5.10.1)
Collecting pyqt5-tools
  Using cached pyqt5_tools-5.15.1.1.7.5-cp37-cp37m-manylinux2014_x86_64.whl (83.3 MB)
Requirement already satisfied: sip<4.20,>=4.19.4 in /usr/lib/python3/dist-packages (from pyqt5) (4.19.21)
Requirement already satisfied: python-dotenv in ./.local/lib/python3.7/site-packages (from pyqt5-tools) (0.14.0)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from pyqt5-tools) (7.0)
Installing collected packages: pyqt5-tools
pyqt5-tools 5.15.1.1.7.5 requires pyqt5==5.15.1, but you'll have pyqt5 5.10.1 which is incompatible.                                                                  
Successfully installed pyqt5-tools-5.15.1.1.7.5

```

Luego de esto, la verdad no sé si quedó peor o mejor.
```
  ╭──luis at GL753VD in ~
  ╰─○ python3.7                                                                    
Python 3.7.9 (default, Aug 18 2020, 02:07:21) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
>>> 
>>> quit()

  ╭──luis at GL753VD in ~
  ╰─○ python3.7                                                                 
Python 3.7.9 (default, Aug 18 2020, 02:07:21) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import QtWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'QtWidgets' from 'PyQt5' (/usr/lib/python3/dist-
>>> quit()
```

Luego de todo ese montón de texto explicando lo que hice sin buenos resultados, **quería pedir ayuda para instalar e importar correctamente PyQt5 (y sus módulos)**.

EDIT: Se cortó la línea del error al final, dice:
`ImportError: cannot import name 'QtWidgets' from 'PyQt5' (/usr/lib/python3/dist-packages/PyQt5/__init__.py)`

**Comment by ljgonzalez1** [comment]
Con ayuda de un amigo encontré una solución. Usar PyCharm para actualizar e instalar paquetes y librerías.
Dejo esto por si alguien llegase a tener el mismo problema. Tal vez le pueda ser de utilidad:

1- Abrir PyCharm (sin ningún proyecto)
![image](https://user-images.githubusercontent.com/48295025/95805340-90b3b680-0cdb-11eb-9799-2c98d940ff58.png)

2- Entrar a configuraciones, en la pestaña de intérprete.
![image](https://user-images.githubusercontent.com/48295025/95805403-b5a82980-0cdb-11eb-9567-1ffbdcc2d260.png)

3- Seleccionar (o agregar) Python 3.7
![image](https://user-images.githubusercontent.com/48295025/95805434-c8226300-0cdb-11eb-8c33-700067c9c38c.png)

4- Instalar y actualizar el PyQt5
4a- Instalar apretando el "+"
![image](https://user-images.githubusercontent.com/48295025/95805562-15063980-0cdc-11eb-8e6f-b6906c659f6e.png)
![image](https://user-images.githubusercontent.com/48295025/95805601-2bac9080-0cdc-11eb-9d83-c91ea37ba8f6.png)

4b- Una vez instalado, seleccionar y actualizar PyQt5 con el triangulo
![image](https://user-images.githubusercontent.com/48295025/95805693-61ea1000-0cdc-11eb-9d33-1c48ab7a0c5a.png)
![image](https://user-images.githubusercontent.com/48295025/95805562-15063980-0cdc-11eb-8e6f-b6906c659f6e.png)

5- Instalar igual que en 4a pyqt5-tools
![image](https://user-images.githubusercontent.com/48295025/95805747-81813880-0cdc-11eb-8804-4028382d1d8a.png)

Y ahí me funcionó.
![image](https://user-images.githubusercontent.com/48295025/95805800-a2e22480-0cdc-11eb-9b87-7da45ea9c9e9.png)
