### ISSUE TITLE
Me sale en el terminal de Spyder: "Ocurrió un error mientras iniciaba el núcleo".

### ISSUE THREAD

**Issue by kikobarros** [IIC2233/syllabus#704]
Estoy tratando de ver que IDLE usar para la tarea pero tengo problema con VSCode, donde me sale "ImportError: DLL load failed: No se puede encontrar el módulo especificado" con PyQt5.tools y en Spyder me pasa esto:
ayuda :(

Traceback (most recent call last):
File "C:\Users\Kiko\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Kiko\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Kiko\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Kiko\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 287, in main
import_spydercustomize()
File "C:\Users\Kiko\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\Kiko\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 27, in 
from IPython.core.getipython import get_ipython
File "C:\Users\Kiko\Anaconda3\lib\site‑packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "C:\Users\Kiko\Anaconda3\lib\site‑packages\IPython\core\application.py", line 18, in 
import logging
File "C:\Users\Kiko\Anaconda3\lib\logging\__init__.py", line 40, in 
import threading
File "C:\Users\Kiko\Desktop\threading.py", line 2, in 
from threading import Thread
ImportError: cannot import name 'Thread' from 'threading' (C:\Users\Kiko\Desktop\threading.py)

**Comment by aaossa** [comment]
@kikobarros en primer lugar, por favor no borres el contenido de la plantilla. Por algo les dejamos la plantilla, para que sigan los pasos pedidos, y por lo mismo les pedimos que no borren sus contenidos 👀 

Sobre tu problema hay dos cosas:

* "IMPORTANTE: En este curso no recomendamos tener instalado ni utilizar Anaconda, ya que el manejo del software obligatorio utilizado en el curso es bastante particular, y extender una instalación de Anaconda puede ser engorroso y dificultar la resolución de problemas. Si tienes Anaconda instalado, recomendamos desinstalarlo y hacer una instalación limpia de Python. " Esto aparece en la [guía de software obligatorio](https://iic2233.github.io/wiki/software), y por lo mismo es difícil que alguien pueda ayudarte con problemas de Spyder 🕷️ 
* Tu problema en particular es que tu archivo se llama `threading.py`, entonces Python se "confunde" cuando intentas importar `threading` de la librería estándar. Solo tienes que cambiarle el nombre a tu archivo de prueba ✨ 

¡Éxito con tu estudio 💪 !
