### ISSUE TITLE
Problema al listar archivo 'posts'

### ISSUE THREAD

**Issue by matiasone** [IIC2233/syllabus#75]
Estimados, estoy tratando de hacer una lista con los post, con el objetivo de borrar publicaciones, pero al correr el código que estoy usando, que si funciona con seguidores.csv y usuarios.csv, me tira este error:

Traceback (most recent call last):
  File "C:/Users/matyf/Desktop/Progra Avanzada/matiasone-iic2233-2020-1/Tareas/T00/Tarea00.py", line 248, in <module>
    lineas = [linea.split() for linea in f]
  File "C:/Users/matyf/Desktop/Progra Avanzada/matiasone-iic2233-2020-1/Tareas/T00/Tarea00.py", line 248, in <listcomp>
    lineas = [linea.split() for linea in f]
  File "C:\Users\matyf\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1521: character maps to <undefined>

**Comment by MatiasDuhalde** [comment]
Hola!

Ya respondimos una issue muy similar en #16 
Probablemente eso logre solucionar tu error, pero si persiste, agrega un comentario en esa issue.
Salu2
