### ISSUE TITLE
Error al escribir "jupyter notebook" en terminal MacOS

### ISSUE THREAD

**Issue by javisantibanez** [IIC2233/Syllabus#8]
Hola, luego de seguir los pasos para instalar Jupyter, al ejecutar el comando jupyter notebook, se me abre una ventana en blanco que contiene solo el logo de Jupyter arriba a la izquierda, mientras que en la terminal me aparece el siguiente código:

```
[I 2023-08-10 17:12:51.873 ServerApp] Package notebook took 0.0000s to import
[I 2023-08-10 17:12:51.875 ServerApp] notebook | extension was successfully linked.
[I 2023-08-10 17:12:51.913 ServerApp] notebook | extension was successfully loaded.
[I 2023-08-10 17:12:51.914 ServerApp] Serving notebooks from local directory: /Users/oliviallanos
[I 2023-08-10 17:12:51.914 ServerApp] Jupyter Server 2.7.0 is running at:
[I 2023-08-10 17:12:51.914 ServerApp] http://localhost:8888/tree?token=680d2a29734f1f0ed1f902b9403e79da37629126061ade1b
[I 2023-08-10 17:12:51.914 ServerApp]     http://127.0.0.1:8888/tree?token=680d2a29734f1f0ed1f902b9403e79da37629126061ade1b
[I 2023-08-10 17:12:51.914 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-08-10 17:12:51.916 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/oliviallanos/Library/Jupyter/runtime/jpserver-60881-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/tree?token=680d2a29734f1f0ed1f902b9403e79da37629126061ade1b
        http://127.0.0.1:8888/tree?token=680d2a29734f1f0ed1f902b9403e79da37629126061ade1b
[W 2023-08-10 17:12:53.583 JupyterNotebookApp] Missing or misshapen translation settings schema:
    HTTP 404: Not Found (Schema not found: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab/schemas/@jupyterlab/translation-extension/plugin.json)
[W 2023-08-10 17:12:53.583 JupyterNotebookApp] Settings directory does not exist at /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab/schemas
[W 2023-08-10 17:12:53.609 JupyterNotebookApp] Missing or misshapen translation settings schema:
    HTTP 404: Not Found (Schema not found: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab/schemas/@jupyterlab/translation-extension/plugin.json)
[W 2023-08-10 17:12:53.609 ServerApp] 404 GET /lab/api/settings/@jupyter-notebook/application-extension:shell?1691701973607 (::1): Schema not found: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab/schemas/@jupyter-notebook/application-extension/shell.json
[W 2023-08-10 17:12:53.609 JupyterNotebookApp] wrote error: 'Schema not found: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab/schemas/@jupyter-notebook/application-extension/shell.json'
    Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/homebrew/lib/python3.10/site-packages/tornado/web.py", line 3290, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/homebrew/lib/python3.10/site-packages/jupyterlab_server/settings_handler.py", line 48, in get
        result, warnings = get_settings(
      File "/opt/homebrew/lib/python3.10/site-packages/jupyterlab_server/settings_utils.py", line 370, in get_settings
        schema, version = _get_schema(schemas_dir, schema_name, overrides, labextensions_path)
      File "/opt/homebrew/lib/python3.10/site-packages/jupyterlab_server/settings_utils.py", line 47, in _get_schema
        raise web.HTTPError(404, notfound_error % path)
    tornado.web.HTTPError: HTTP 404: Not Found (Schema not found: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab/schemas/@jupyter-notebook/application-extension/shell.json)
[W 2023-08-10 17:12:53.611 JupyterNotebookApp] 404 GET /lab/api/settings/@jupyter-notebook/application-extension:shell?1691701973607 (07083e89f5584385899dde25b6f9a871@::1) 2.95ms referer=http://localhost:8888/tree
[W 2023-08-10 17:12:53.612 JupyterNotebookApp] Missing or misshapen translation settings schema:
    HTTP 404: Not Found (Schema not found: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab/schemas/@jupyterlab/translation-extension/plugin.json)
[W 2023-08-10 17:12:53.612 ServerApp] 404 GET /lab/api/settings/@jupyterlab/translation-extension:plugin?1691701973607 (::1): Schema not found: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab/schemas/@jupyterlab/translation-extension/plugin.json
[W 2023-08-10 17:12:53.613 JupyterNotebookApp] wrote error: 'Schema not found: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab/schemas/@jupyterlab/translation-extension/plugin.json'
    Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/homebrew/lib/python3.10/site-packages/tornado/web.py", line 3290, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/homebrew/lib/python3.10/site-packages/jupyterlab_server/settings_handler.py", line 48, in get
        result, warnings = get_settings(
      File "/opt/homebrew/lib/python3.10/site-packages/jupyterlab_server/settings_utils.py", line 370, in get_settings
        schema, version = _get_schema(schemas_dir, schema_name, overrides, labextensions_path)
      File "/opt/homebrew/lib/python3.10/site-packages/jupyterlab_server/settings_utils.py", line 47, in _get_schema
        raise web.HTTPError(404, notfound_error % path)
    tornado.web.HTTPError: HTTP 404: Not Found (Schema not found: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab/schemas/@jupyterlab/translation-extension/plugin.json)
```

![56EC7035-3B0C-4DAD-9928-A2927826515F](https://github.com/IIC2233/Syllabus/assets/141786962/de44ec95-cefb-4738-bd8c-ad3bd691b7fb)

**Comment by Hernan4444** [comment]
Hola @javisantibanez 

Por si acaso, ¿ya instalaste git? (para verificar si tienes el comando `brew`). Que una opción es que primero desinstales jupyter notebook (`python3 -m pip uninstall notebook`) y luego hacer `brew install jupyter`. Esto es otra forma de instalar jupyter notebook.

Luego, reiniciar el pc para asegurarse que todos los cambios hagan efectos, e intentar  hacer `jupyter notebook`.

Cuantanos cómo te va con esto, para descargar posibles soluciones,
Saludosヾ(＾-＾)ノ

**Comment by javisantibanez** [comment]
Hola @Hernan4444, seguí los pasos y se me solucionó el problema, mucha gracias!

**Comment by javisantibanez** [comment]
Hola @Hernan4444, seguí los pasos y se me solucionó el problema, mucha gracias!

**Comment by Hernan4444** [comment]
Hola @javisantibanez 

¡Que bueno! Dejaré la issue abierta un tiempo para que otras personas puedan ver la solución. Luego nosotros cerramos la issue.

Saludos!
