### ISSUE TITLE
Servidor al cerrarse genera OSError: [WinError 10038] de forma esporadica

### ISSUE THREAD

**Issue by JaToledo99** [IIC2233/syllabus#801]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/681)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Mi servidor lo puedo ejecutar y cerrar varias veces consecutivas en el mismo adress (port y host) puesto que cierro el socket y mis threads son todos daemon. Pero a veces se genera este error, es al azar al parecer. Si ejecuto varias veces seguidas el servidor cerrandolo cada vez, sin cambiar nada de codigo, a veces imprime esto, y las demas veces nada:

Traceback (most recent call last):
  File "C:\Users\NOTEBOOK\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\NOTEBOOK\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\NOTEBOOK\Desktop\Progra Avanzada 2021\JaToledo99-iic2233-2021-1\Tareas\T3\server\server.py", line 54, in accept_connections_thread
    client_socket, _ = self.socket_server.accept()
  File "C:\Users\NOTEBOOK\AppData\Local\Programs\Python\Python37\lib\socket.py", line 212, in accept
    fd, addr = self._accept()
OSError: [WinError 10038] An operation was attempted on something that is not a socket

**Comment by knight-who-say-ni** [comment]
Hola @JaToledo99!!

Estuve investigando, y al parecer ese error pasa porque estás tratando de enviar información a un socket despues de que este fue cerrado. Te recomiendo buscar las lineas donde cierres los sockets, puede ser que alguno se está cerrando en un momento inadecuado.

Saludos!!
