### ISSUE TITLE
Error al recibir informacion en servidor

### ISSUE THREAD

**Issue by criss-ah** [IIC2233/syllabus#837]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/681)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Al momento de enviar información desde cliente al servidor y establecer conexión, en servidor me arroja el siguiente error en el lock que no logro entender:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\canto\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\canto\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\canto\criss-ah-iic2233-2021-1\Tareas\T3\servidor\servidor_.py", line 35, in aceptar_clientes
    with self.lock_clientes_conectados:
AttributeError: __enter__
De antemano, muchas gracias por la respuesta.

**Comment by mariizamb** [comment]
Tngo exactamente el mismo error pero de servidor a cliente :(
