### ISSUE TITLE
Error al importar señal, funciona sin la funcion keyPressEvent 

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#858]
El error:

Traceback (most recent call last):
  File "/home/usuario/UNI2020/PA/sofiuni/sofiuni-iic2233-2020-1/Tareas/T02/ventana_juego_principal.py", line 141, in keyPressEvent
    self.dccafe.actualizar_dinero(10)
  File "/home/usuario/UNI2020/PA/sofiuni/sofiuni-iic2233-2020-1/Tareas/T02/dccafe.py", line 9, in actualizar_dinero
    s.senales.senal_dinero_cambia.emit()
NameError: name 's' is not defined
Aborted (core dumped)

Funcionaba todo perfecto antes de programar esta función y ahora me dice que s no existe pero s es declarado en el import, por que dice que no existe s?

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

Revisé tu código y este cambió desde que publicaste la *issue*. ¿Pudiste solucionarlo?

Saludos.
