### ISSUE TITLE
Desserializar con json

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#861]
Hola, me puse a revisar cómo desserializar un json a un objeto creado por mí, pero no logro descubrir cómo se hace.

Lo primero que probé fue hacer esto:
```python
import json


class A:
    def __init__(self, v1, v2):
        self.name = f"Soy {v1}"
        self.value = (v1 + v2**4/v1**3)
        self.other_value = v1 - v2

    def __str__(self):
        return str(self.__dict__)


class ADecoder(json.JSONDecoder):
    def default(self, obj):
        o = A(1, 1)
        o.name = obj["name"]
        o.value = obj["value"]
        o.other_value = obj["other_value"]
        return o


a1 = A(5, 8)
print(a1)
print(type(a1))
serializado = json.dumps(a1.__dict__)

a2 = json.loads(serializado, cls=ADecoder)
print(a2)
print(type(a2))
```
Pero me retorna:
```
{'name': 'Soy 5', 'value': 37.768, 'other_value': -3}
<class '__main__.A'>
{'name': 'Soy 5', 'value': 37.768, 'other_value': -3}
<class 'dict'>
```

Y me debería estar retornando un objeto de la clase A y no un diccionario :(

También intenté
```python
decoder = ADecoder()

a1 = A(5, 8)
print(a1)
print(type(a1))
serializado = json.dumps(a1.__dict__)

a2 = decoder.decode(serializado)
print(a2)
print(type(a2))
```
obteniendo el mismo resultado que antes y esto:
```python
decoder = ADecoder()

a1 = A(5, 8)
print(a1)
print(type(a1))
serializado = json.dumps(a1.__dict__)

a2 = decoder.decode(serializado, _w=A)
print(a2)
print(type(a2))
```
me empieza a tirar errores como si estuviera llamando al `__init__` del objeto :/

```
{"name": "Soy 5", "value": 37.768, "other_value": -3} 0
Traceback (most recent call last):
  File "C:\Users\Jose\Desktop\prueba.py", line 31, in <module>
    a2 = decoder.decode(serializado, _w=A)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Jose\Desktop\prueba.py", line 8, in __init__
    self.value = (v1 + v2**4/v1**3)
TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'
```
(ahí le agregué un print(v1, v2) al init de A y me pone en v1 el diccionario completo y en v2 un cero :/

**Y no encuentro info en google al respecto 😩😩**

**Comment by santilaguna** [comment]
Hola, recuerda que igual lo puedes deserializar con object_hook y con una función que reciba el diccionario que retorna json y lo convierta en una clase!
