### ISSUE TITLE
SyntaxError al incorporar la interfaz al código

### ISSUE THREAD

**Issue by nvaldiviesoo** [IIC2233/syllabus#865]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! 
Tengo un problema al incorporar la interfaz al código, muy similar al issue #782, pero en su caso encontraron una solución que a mí no me sirve. 

Resulta que diseñé la ventana de juego con QT Designer, seguí el procedimiento para incorporarla al código en python, pero a la hora de ejecutarlo, me arroja 

```
SyntaxError: invalid syntax
MacBook-Pro-de-Niko:T02 Niko$ /usr/local/bin/python3 /Users/Niko/Desktop/programacion_avanzada/nvaldiviesoo-iic2233-2020-2/Tareas/T02/ventana_de_juego.py
Traceback (most recent call last):
  File "/Users/Niko/Desktop/programacion_avanzada/nvaldiviesoo-iic2233-2020-2/Tareas/T02/ventana_de_juego.py", line 5, in <module>
    window_name, base_class = uic.loadUiType("qt_ventana_juego.ui")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/uic/__init__.py", line 201, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 130
    self.0 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
```

Intenté con una solución de google, convirtiendo el archivo `.ui` a `.py` con `pyuic5`, pero aun así me arroja el `SyntaxError self.0 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)` al correr el archivo `.py` con esta ventana

(En algún momento al probar soluciones a mi código solo le cambié el archivo `.ui`  por uno mucho más simple (que contenía solo un botón) y ahí sí se abrió la ventana sin probelma)

¿Alguna idea de cómo solucionarlo?
De antemano muchas gracias

**Comment by nvaldiviesoo** [comment]
NO PASA NADA. YA LO SOLUCIONÉ.
