### ISSUE TITLE
Problemas para correr los test

### ISSUE THREAD

**Issue by JSalas277** [IIC2233/Syllabus#92]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Tengo problemas para correr los test, pues al parecer algo le esta ocurriendo al dcciudad siendo que me aparece esto:

Traceback (most recent call last):
  File "C:\Users\joesa\Documents\JSalas277-iic2233-2024-1\Tareas\T1\todos_tests.py", line 2, in <module>
    from tests_publicos.test_00_informacion_red import TestInformacionRed
  File "C:\Users\joesa\Documents\JSalas277-iic2233-2024-1\Tareas\T1\tests_publicos\test_00_informacion_red.py", line 8, in <module>
    from red import RedMetro
  File "C:\Users\joesa\Documents\JSalas277-iic2233-2024-1\Tareas\T1\red.py", line 1, in <module>
    import dcciudad
ImportError: bad magic number in 'dcciudad': b'\xa7\r\r\n'

**Comment by JSalas277** [comment]
Ya lo resolvi
